auctions/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register")
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("wiki/", views.index, name="index"),
    path("wiki/<str:entry>", views.viewentry, name="entry"),
    path("wiki/search/", views.search, name="search"),
    path("wiki/newentry/", views.newentry, name="newentry"),
    path("wiki/editpage/<str:entry>", views.editpage, name="editpage"),
    path("wiki/randompage/", views.randompage, name="randompage")
    

]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

handler404 = 'encyclopedia.views.error_404'
handler500 = 'encyclopedia.views.error_500'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    pass

encyclopedia/models.py
from django.db import models

# Create your models here.

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .models import User


def index(request):
    return render(request, "auctions/index.html")


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "auctions/register.html")

encyclopedia/views.py
import re
from django.http import HttpResponse, HttpResponseNotFound
from django.shortcuts import redirect, render
from markdown import markdown

from . import util

import random


def index(request):
    return render(request, "encyclopedia/index.html", {
            "entries": util.list_entries()
        })

def viewentry(request, entry):

    try:
        return render(request, "encyclopedia/viewentry.html", {
                "entry": markdown(util.get_entry(entry)),
                "entrytitle": entry
            })
    except:
        return render(request, "encyclopedia/viewentry.html", {
            "entry": "Sorry, the page you requested does not exist!",
            "entrytitle": "Page Not Found"
        })

def search(request):
    if request.method == 'POST':
        query = request.POST.get('q')
        entries = []
        searchentries = []

        for ent in util.list_entries():
            entries.append(ent.lower())
        if query.lower() in entries:        
            redirect_url = f"/wiki/{query}"
            return redirect(redirect_url)
        else:
            for entry in entries:
                if query.lower() in entry:
                    searchentries.append(entry)
                    entry =+ 1
                elif query.lower() not in entry:
                    entry =+ 1
            if len(searchentries) == 0:
                return render(request, "encyclopedia/search.html", {
                    "message": "Sorry, no entries found!"
                })
            else:
                return render(request, "encyclopedia/search.html", {
                "searchentries": searchentries,
                "message": "Are you looking for:"
                    })

def newentry(request):
    if request.method == 'POST':
        n_title = request.POST.get('n_title')
        n_cont = request.POST.get('n_cont')
        mdtitle = f"# {n_title}\n"

        if n_title in util.list_entries():
            return render(request, "encyclopedia/viewentry.html", {
                "entrytitle": "Page Already Exists!",
                "entry": "Sorry, but the page you're trying to create already exits!"
            })
        else:
            util.save_entry(n_title, mdtitle + n_cont)
            return viewentry(request, n_title)
    else:
        return render(request, "encyclopedia/modifyentry.html", {
            "label": "Create a new entry",
            "title_label": "Name Your Article:",
            "cont_label": "Write a Description:"
        })

def editpage(request, entry):

    if request.method == 'POST':
        e_cont = request.POST.get('n_cont')
        
        util.save_entry(entry, bytes(e_cont, 'utf8'))
        return viewentry(request, entry)
    
    else:

        return render(request, "encyclopedia/modifyentry.html", {
            "label": "Edit Page",
            "title_label": "Rename Article:",
            "cont_label": "Modify Content:",
            "e_title": entry,
            "e_content": util.get_entry(entry)                 
        })

def randompage(request):
    
    entries = []
    for ent in util.list_entries():
        entries.append(ent.lower())
    
    return viewentry(request, random.choice(entries))


def error_404(request, exception):
    return render(request, "encyclopedia/viewentry.html",{
        "entry": "Sorry, your requested URL was not found!",
        "entrytitle": "Entry not found"
    })

def error_500(request):
    return render(request, "encyclopedia/viewentry.html",{
        "entry": "Sorry, an error occurred!",
        "entrytitle": "Error"
    })
    
        

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Active Listings</h2>

    TODO
{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <h1>Auctions</h1>
        <div>
            {% if user.is_authenticated %}
                Signed in as <strong>{{ user.username }}</strong>.
            {% else %}
                Not signed in.
            {% endif %}
        </div>
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'index' %}">Active Listings</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'register' %}">Register</a>
                </li>
            {% endif %}
        </ul>
        <hr>
        {% block body %}
        {% endblock %}
    </body>
</html>

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'register' %}">Register here.</a>

{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'login' %}">Log In here.</a>

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="/wiki/{{entry}}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'encyclopedia/styles.css' %}">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="POST">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:newentry' %}">Create New Page</a>
                </div>
                <div>
                    <a href ="{% url 'encyclopedia:randompage' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9" id="body_ind">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/modifyentry.html
{% extends "encyclopedia/layout.html" %}

{% block title %} {{label | title}} {% endblock %}

{% block body %}

    <h1 style="margin-left: 10px;">{{label | title}}</h1><br>
    
    {% if e_content %}
        <div></div>
    {% else %}
    <div>
        <h3 style="margin-left: 10px;">{{title_label}}</h3>
        <textarea form="modentryform" placeholder="Title" id="n_titletxt" name="n_title">{{e_title}}</textarea>
    </div>
    
    {% endif %}

    <div>
        <h3 style="margin-left: 10px;">{{cont_label}}</h3>
        <textarea form="modentryform" placeholder="Content" id="n_bodytxt" name="n_cont">{{e_content}}</textarea>
    </div>

    <div>
        {% if e_content %}
            <form action="/wiki/editpage/{{e_title}}" method="POST" id="modentryform">
                {% csrf_token %}
                <input type="submit" value="Save" style="margin: 10px">
            </form>
        {% else %}        
            <form action="{% url 'encyclopedia:newentry' %}" method="POST" id="modentryform">
                {% csrf_token %}
                <input type="submit" value="Save" style="margin: 10px">
            </form>
        {% endif %}
    </div>


{% endblock %}

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title%} Search Results {% endblock %}

{% block body %}
    {{message}}
{% for searchentry in searchentries %}  
<ul>
    <a href = "/wiki/{{searchentry}}"> <li>{{searchentry | title}}</li> </a>
</ul>

{% endfor %}
{% endblock %}

encyclopedia/templates/encyclopedia/viewentry.html
{% extends "encyclopedia/layout.html" %}

{% block title %} {{entrytitle | title}} {% endblock %}

{% block body %}

    <div style="text-align: right; margin-right: 25px;">
        <a href="/wiki/editpage/{{entrytitle}}">Edit page✎</a>
    </div>

    {{entry | safe}}


{% endblock %}